[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_API_HOST/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://YOUR_API_HOST/health"
  status = 200
  force = true